name: Azure Container Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: |
          docker login ${{ secrets.AZURE_LOGIN_SERVER }} -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t myapp-image .
          docker tag myapp-image ${{ secrets.AZURE_LOGIN_SERVER }}/myapp-image:latest
          docker push ${{ secrets.AZURE_LOGIN_SERVER }}/myapp-image:latest

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: your-app-name  # Replace with your Azure Web App name
          images: ${{ secrets.AZURE_LOGIN_SERVER }}/myapp-image:latest
